services:
  chrono_api:
    build: .

    ports:
      - "5001:5001"

    environment:
      SCRAPER_SERVICE_URL: "http://letmerent-scraper_api_1:5000"
      OLD_LISTINGS_DAYS: "30"
      SCHEDULER_INTERVAL_MINUTES: "10"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "letmerent.notifications@gmail.com"
      SMTP_PASSWORD: "kkvwclskttupqwvv"
      EMAIL_FROM: "letmerent.notifications@gmail.com"

    networks:
      - mongodb_dev_net

networks:
  mongodb_dev_net:
    external: true